# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 爆开的个人博客
subtitle: ''
description: ''
keywords:
author: Glk
language: zh-CN
timezone: ''



# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://yoursite.com
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing index.html from permalinks


# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:		#如果也有别的页面不需要渲染，直接在下方添加就可以了
    - 404.html		#将404.html加进去，【-】之后要有空格隔开

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## Use post's date for updated date unless set in front-matter
use_date_for_updated: false

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: icarus

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: https://github.com/glk-hll/glk-hll.github.io.git
  branch: master

live2d:
	enable: true
	scriptFrom: local
	model: 
		use: live2d-widget-model-haruto # live2d-widget-model-epsilon2_1 #模型选择 1. live2d-widget-model-haruto(卡通男) 2. live2d-widget-model-epsilon2_1(灰头卡通连衣裙女) 3. live2d-widget-model-gf(卡通大刀勇士) 4. live2d-widget-model-miku()

    # live2d-widget-model-chitose 西装男超级丑
    # live2d-widget-model-epsilon2_1 黄衣少女
    # live2d-widget-model-gf
    # live2d-widget-model-haru/01 (use npm install --save live2d-widget-model-haru)
    # live2d-widget-model-haru/02 (use npm install --save live2d-widget-model-haru)
    # live2d-widget-model-haruto
    # live2d-widget-model-hibiki
    # live2d-widget-model-hijiki
    # live2d-widget-model-izumi
    # live2d-widget-model-koharu
    # live2d-widget-model-miku
    # live2d-widget-model-ni-j
    # live2d-widget-model-nico
    # live2d-widget-model-nietzsche
    # live2d-widget-model-nipsilon
    # live2d-widget-model-nito
    # live2d-widget-model-shizuku
    # live2d-widget-model-tororo
    # live2d-widget-model-tsumiki
    # live2d-widget-model-unitychan
    # live2d-widget-model-wanko
    # live2d-widget-model-z16

	display: 
		position: right  #模型位置
		width: 150       #模型宽度
		height: 300      #模型高度
	mobile: 
		show: true      #是否在手机端显示

# hexo-admin authentification
admin:
  username: glk
  password_hash: $2a$10$9YGrC2cJQZaWXRNxf0dIZOX2Uxg41s.5xK6D.nm6rSrq1472CFWIa
  secret: cisco_psd
